package sticker

import (
	"bytes"
	"image"
	"image/color"
	"image/png"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/Chuntttttt/tapedeck/internal/models"
)

func TestNewGenerator(t *testing.T) {
	gen := NewGenerator(false)
	if gen == nil {
		t.Fatal("NewGenerator returned nil")
	}
}

func TestFetchPosterImage(t *testing.T) {
	// Create a simple 1x1 test image programmatically
	testImg := image.NewRGBA(image.Rect(0, 0, 1, 1))
	testImg.Set(0, 0, color.RGBA{255, 0, 0, 255}) // Red pixel

	// Encode to PNG
	var buf bytes.Buffer
	if err := png.Encode(&buf, testImg); err != nil {
		t.Fatalf("Failed to encode test image: %v", err)
	}
	pngData := buf.Bytes()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "image/png")
		_, _ = w.Write(pngData)
	}))
	defer server.Close()

	gen := NewGenerator(true)
	img, err := gen.fetchPosterImage(server.URL)
	if err != nil {
		t.Fatalf("fetchPosterImage failed: %v", err)
	}
	if img == nil {
		t.Fatal("fetchPosterImage returned nil image")
	}
}

func TestFetchPosterImage_InvalidURL(t *testing.T) {
	gen := NewGenerator(true)
	// Use localhost with a port that's unlikely to be listening
	_, err := gen.fetchPosterImage("http://localhost:59999/nonexistent.png")
	if err == nil {
		t.Fatal("Expected error for invalid URL")
	}
}

func TestExtractDominantColor(t *testing.T) {
	// Create a simple test image with red edges
	img := image.NewRGBA(image.Rect(0, 0, 100, 100))
	red := color.RGBA{255, 0, 0, 255}

	// Fill edges with red
	for x := 0; x < 100; x++ {
		img.Set(x, 0, red)  // Top edge
		img.Set(x, 99, red) // Bottom edge
	}
	for y := 0; y < 100; y++ {
		img.Set(0, y, red)  // Left edge
		img.Set(99, y, red) // Right edge
	}

	gen := NewGenerator(false)
	dominantColor := gen.extractDominantColor(img)

	r, g, b, _ := dominantColor.RGBA()
	// Convert from 16-bit to 8-bit
	r8, g8, b8 := uint8(r>>8), uint8(g>>8), uint8(b>>8) //nolint:gosec // Shifting by 8 ensures values fit in uint8

	// Should be reddish (darkened by 20%)
	if r8 < 150 || g8 > 50 || b8 > 50 {
		t.Errorf("Expected reddish color, got R=%d G=%d B=%d", r8, g8, b8)
	}
}

func TestGeneratePDF(t *testing.T) {
	gen := NewGenerator(false)

	// Create test mappings
	mappings := []*models.CardMapping{
		{
			ID:           1,
			MediaTitle:   "Test Movie",
			MediaType:    "movie",
			ThumbnailURL: "", // Empty URL for placeholder test
		},
	}

	pdfBytes, err := gen.GeneratePDF(mappings, "test-token")
	if err != nil {
		t.Fatalf("GeneratePDF failed: %v", err)
	}

	if len(pdfBytes) == 0 {
		t.Fatal("GeneratePDF returned empty bytes")
	}

	// Verify PDF signature
	if !bytes.HasPrefix(pdfBytes, []byte("%PDF")) {
		t.Fatal("Generated bytes are not a valid PDF")
	}
}
